const ALPHABET: Data.Alphabet = [
  { id: "1", character: "ა", name: "ani", type: "vowel", nationalSystem: "a" },
  {
    id: "2",
    character: "ბ",
    name: "bani",
    type: "consonant",
    nationalSystem: "b",
  },
  {
    id: "3",
    character: "გ",
    name: "gani",
    type: "consonant",
    nationalSystem: "g",
  },
  {
    id: "4",
    character: "დ",
    name: "doni",
    type: "consonant",
    nationalSystem: "d",
  },
  { id: "5", character: "ე", name: "eni", type: "vowel", nationalSystem: "e" },
  {
    id: "6",
    character: "ვ",
    name: "vini",
    type: "consonant",
    nationalSystem: "v",
  },
  {
    id: "7",
    character: "ზ",
    name: "zani",
    type: "consonant",
    nationalSystem: "z",
  },
  {
    id: "8",
    character: "თ",
    name: "tani",
    type: "consonant",
    nationalSystem: "t",
  },
  { id: "9", character: "ი", name: "ini", type: "vowel", nationalSystem: "i" },
  {
    id: "10",
    character: "კ",
    name: "k'ani",
    type: "consonant",
    nationalSystem: "k",
  },
  {
    id: "11",
    character: "ლ",
    name: "lani",
    type: "consonant",
    nationalSystem: "l",
  },
  {
    id: "12",
    character: "მ",
    name: "mani",
    type: "consonant",
    nationalSystem: "m",
  },
  {
    id: "13",
    character: "ნ",
    name: "nari",
    type: "consonant",
    nationalSystem: "n",
  },
  { id: "14", character: "ო", name: "oni", type: "vowel", nationalSystem: "o" },
  {
    id: "15",
    character: "პ",
    name: "p'ari",
    type: "consonant",
    nationalSystem: "p",
  },
  {
    id: "16",
    character: "ჟ",
    name: "zhani",
    type: "consonant",
    nationalSystem: "zh",
  },
  {
    id: "17",
    character: "რ",
    name: "rani",
    type: "consonant",
    nationalSystem: "r",
  },
  {
    id: "18",
    character: "ს",
    name: "sani",
    type: "consonant",
    nationalSystem: "s",
  },
  {
    id: "19",
    character: "ტ",
    name: "t'ari",
    type: "consonant",
    nationalSystem: "t'",
  },
  { id: "20", character: "უ", name: "uni", type: "vowel", nationalSystem: "u" },
  {
    id: "21",
    character: "ფ",
    name: "phari",
    type: "consonant",
    nationalSystem: "ph",
  },
  {
    id: "22",
    character: "ქ",
    name: "khani",
    type: "consonant",
    nationalSystem: "kh",
  },
  {
    id: "23",
    character: "ღ",
    name: "ghani",
    type: "consonant",
    nationalSystem: "gh",
  },
  {
    id: "24",
    character: "ყ",
    name: "q'ari",
    type: "consonant",
    nationalSystem: "q",
  },
  {
    id: "25",
    character: "შ",
    name: "shani",
    type: "consonant",
    nationalSystem: "sh",
  },
  {
    id: "26",
    character: "ჩ",
    name: "chani",
    type: "consonant",
    nationalSystem: "ch",
  },
  {
    id: "27",
    character: "ც",
    name: "tsani",
    type: "consonant",
    nationalSystem: "ts",
  },
  {
    id: "28",
    character: "ძ",
    name: "dzani",
    type: "consonant",
    nationalSystem: "dz",
  },
  {
    id: "29",
    character: "წ",
    name: "ts'ani",
    type: "consonant",
    nationalSystem: "ts'",
  },
  {
    id: "30",
    character: "ჭ",
    name: "ch'ani",
    type: "consonant",
    nationalSystem: "ch'",
  },
  {
    id: "31",
    character: "ხ",
    name: "khani",
    type: "consonant",
    nationalSystem: "kh",
  },
  {
    id: "32",
    character: "ჯ",
    name: "jani",
    type: "consonant",
    nationalSystem: "j",
  },
  {
    id: "33",
    character: "ჰ",
    name: "hani",
    type: "consonant",
    nationalSystem: "h",
  },
];

export { ALPHABET };
